version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.4

    steps:
      - checkout

      - run:
          name: make html
          command: |
            sudo pip install jupyter
            sudo pip install nbconvert
            sudo pip install matplotlib
            sudo pip install numpy
            sudo pip install sklearn            
            jupyter nbconvert --execute homework.ipynb

      - store_artifacts:
          path: homework.html
          destination: homework.html    