version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.4

    working_directory: ~/repo


    steps:
      - checkout

      - run:
          name: make html
          command: |
            sudo pip install nbconvert
            sudo pip install jupyter_client
            jupyter nbconvert --execute homework.ipynb

      - store_artifacts:
          path: homework.html
          destination: homework.html    